services:
  # 服务名称，可以用任意你喜欢的名字
  nextjs_app:
    # 构建镜像使用的 Dockerfile 路径
    build:
      context: .
      dockerfile: Dockerfile
    # 端口映射，将容器的 3000 端口映射到宿主机的 3000 端口
    ports:
      - "9004:3000"
    # 环境变量，如果需要可以在这里定义
    environment:
      - NODE_ENV=production
    # 容器启动后执行的命令，这里使用 npm 启动 Next.js 应用
    command: ["npm", "start"]
    networks:
      - 1panel-network

networks:
  1panel-network:
    external: true
